export default {
    showEye: require('../assets/images/show.png'),
    hideEye: require('../assets/images/hide.png'),
    icBakc: require('../assets/images/back.png'),
    icForward: require('../assets/images/forward.png'),
    home: require('../assets/images/home.png'),
    profile: require('../assets/images/profile.png'),
    booking: require('../assets/images/booking.png'),
    notification: require('../assets/images/notification.png'),
    Location: require('../assets/images/location.png'),
    Medicine: require('../assets/images/medicine.png'),
    Add: require('../assets/images/add.png'),
    bell: require('../assets/images/bell.png'),
    ActiveRadio: require('../assets/images/radioActice.png'),
    InactiveRadio: require('../assets/images/radioInactive.png'),
    Pencil: require('../assets/images/editPencil.png'),
    DropdownArrow: require('../assets/images/dropArrow.png'),
    Close: require('../assets/images/close.png'),
    Checked: require('../assets/images/checked.png'),
    Doctor: require('../assets/images/doctor.png'),
    ProgressBar: require('../assets/images/progress.png'),
    Team: require('../assets/images/team.png'),
    logo: require('../assets/images/logo.png'),
    setting: require('../assets/images/setting.png'),
}