export default [
    {name : 'IU', value:'IU'},
    {name : 'ampoule(s)', value:'ampoule(s)'},
    {name : 'applications(s)', value:'applications(s)'},
    {name : 'capsule(s)', value:'capsule(s)'},
    {name : 'drop(s)', value:'drop(s)'},
    {name : 'gram(s)', value:'gram(s)'},
    {name : 'injection(s)', value:'injection(s)'},
    {name : 'milligram(s)', value:'milligram(s)'},
    {name : 'milliliter(s)', value:'milliliter(s)'},
    {name : 'packet(s)', value:'packet(s)'},
    {name : 'patch(es)', value:'patch(es)'},
    {name : 'pessary(ies)', value:'pessary(ies)'},
    {name : 'piece(s)', value:'piece(s)'},
    {name : 'pill(s)', value:'pill(s)'},
    {name : 'puff(s)', value:'puff(s)'},
    {name : 'spray(s)', value:'spray(s)'},
    {name : 'suppository(s)', value:'suppository(s)'},
    {name : 'tablespoon(s)', value:'tablespoon(s)'},
    {name : 'unit(s)', value:'unit(s)'},
    {name : 'vaginal capsule(s)', value:'vaginal capsule(s)'},
    {name : 'vaginal insert(S)', value:'vaginal insert(s)'},
    {name : 'vaginal tablet(s)', value:'vaginal tablet(s)'},
]