export default [
    {name : 'IU', value:'IU'},
    {name : 'ampoule(s)', value:'ampoule'},
    {name : 'applications(s)', value:'applications'},
    {name : 'capsule(s)', value:'capsule'},
    {name : 'drop(s)', value:'drop'},
    {name : 'gram(s)', value:'gram'},
    {name : 'injection(s)', value:'injection'},
    {name : 'milligram(s)', value:'milligram'},
    {name : 'milliliter(s)', value:'milliliter'},
    {name : 'packet(s)', value:'packet'},
    {name : 'patch(es)', value:'patch'},
    {name : 'pessary(ies)', value:'pessary'},
    {name : 'piece(s)', value:'piece'},
    {name : 'pill(s)', value:'pill'},
    {name : 'puff(s)', value:'puff'},
    {name : 'spray(s)', value:'spray'},
    {name : 'suppository(s)', value:'suppository'},
    {name : 'tablespoon(s)', value:'tablespoon'},
    {name : 'unit(s)', value:'unit'},
    {name : 'vaginal capsule(s)', value:'vaginal capsule'},
    {name : 'vaginal insert(S)', value:'vaginal insert'},
    {name : 'vaginal tablet(s)', value:'vaginal tablet'},
]